[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Fedor Uvarychev <ufispb@gmail.com>"]
edition = "2018"

[dependencies]
ferris-says  = "0.1"

[[bin]]
name = "structs"
path = "src/02-structs.rs"
